/**
 * HARSI+CBC
 *
 * Heikin-Ashi candles of the zero-centred RSI (RSI - 50) of close, high and low: open = previous close RSI,
 * high / low = the larger / smaller of the high and low RSI, close = the average of the four; the candle open is
 * smoothed as a Heikin-Ashi open ((open[1] * smoothing + close[1]) / (smoothing + 1)). A zero-centred RSI of the
 * source (optionally smoothed: (previous + current) / 2) is drawn as a line with a shadow and as a histogram, and an
 * optional stochastic of that RSI (scaled) as K / D lines or a ribbon fill. Bands at OB / OS levels with fills.
 * CBC flip: the state turns bullish when the close is above the previous high and bearish when the close is below
 * the previous low; a flip colours the background and draws a triangle.
 *
 * Reference: "HARSI+CBC" by mehmetbezgincan
 * Licence: Mozilla Public License 2.0, as the original Pine script (https://mozilla.org/MPL/2.0/).
 * Original notice: This source code is free to use, copy, and alter in any way you choose. ...but credit is always
 * nice :) HARSI Originally by @JayRogers. CBC Flip Originally by @friksa & @AsiaRoo
 */

import { ta, Series, getSourceSeries, color, type IndicatorResult, type InputConfig, type PlotConfig, type HLineConfig, type FillConfig, type Bar, type SourceType } from 'oakscriptjs';
import type { MarkerData, PlotCandleData, BgColorData } from '../types';

export interface HarsiCbcInputs {
  /** RSI length of the HARSI candles */
  lenHARSI: number;
  /** Smoothing of the candle open */
  smoothing: number;
  colUp: string;
  colDown: string;
  colWick: string;
  /** Source of the RSI plot */
  source: SourceType;
  /** RSI plot length */
  lenRSI: number;
  /** Smoothed RSI plot */
  mode: boolean;
  showPlot: boolean;
  showHist: boolean;
  showStoch: boolean;
  /** Stochastic as a ribbon fill (K / D lines transparent) */
  ribbon: boolean;
  smoothK: number;
  smoothD: number;
  stochLen: number;
  /** Stochastic scaling (%) */
  stochFit: number;
  upper: number;
  upperx: number;
  lower: number;
  lowerx: number;
  showCbcBg: boolean;
  showCbcShapes: boolean;
}

export const defaultInputs: HarsiCbcInputs = {
  lenHARSI: 14,
  smoothing: 1,
  colUp: color.teal,
  colDown: color.red,
  colWick: color.gray,
  source: 'ohlc4',
  lenRSI: 7,
  mode: true,
  showPlot: true,
  showHist: true,
  showStoch: false,
  ribbon: true,
  smoothK: 3,
  smoothD: 3,
  stochLen: 14,
  stochFit: 80,
  upper: 20,
  upperx: 30,
  lower: -20,
  lowerx: -30,
  showCbcBg: true,
  showCbcShapes: true,
};

const G_CAND = 'Config » HARSI Candles';
const G_PLOT = 'Config » RSI Plot';
const G_STOCH = 'Config » Stochastic RSI Plot';
const G_CHAN = 'Config » OB/OS Boundaries';
const G_CBC = 'Config » CBC Flip';

export const inputConfig: InputConfig[] = [
  { id: 'lenHARSI', type: 'int', title: 'Length', defval: 14, min: 1, group: G_CAND,
    tooltip: 'Period for the RSI calculations used to generate the candles.' },
  { id: 'smoothing', type: 'int', title: 'Open Smoothing', defval: 1, min: 1, max: 100, group: G_CAND,
    tooltip: 'Smoothing feature for the OPEN of the HARSI candles.' },
  { id: 'colUp', type: 'color', title: 'Colour Pallette  ', defval: color.teal, group: G_CAND, inline: 'Colour Pallette' },
  { id: 'colDown', type: 'color', title: ' ', defval: color.red, group: G_CAND, inline: 'Colour Pallette' },
  { id: 'colWick', type: 'color', title: ' ', defval: color.gray, group: G_CAND, inline: 'Colour Pallette' },
  { id: 'source', type: 'source', title: 'Source', defval: 'ohlc4', group: G_PLOT },
  { id: 'lenRSI', type: 'int', title: 'Length', defval: 7, min: 1, group: G_PLOT },
  { id: 'mode', type: 'bool', title: 'Smoothed Mode RSI?', defval: true, group: G_PLOT,
    tooltip: 'Smoothes the RSI in a manner similar to HA open, but uses the realtime rsi rather than the prior close value.' },
  { id: 'showPlot', type: 'bool', title: 'Show RSI Plot?', defval: true, group: G_PLOT },
  { id: 'showHist', type: 'bool', title: 'Show RSI Histogram?', defval: true, group: G_PLOT },
  { id: 'showStoch', type: 'bool', title: 'Show Stochastic? ', defval: false, group: G_STOCH, inline: 'Stoch Draw States',
    tooltip: 'Uses the RSI generated by the above settings, and will be affected by the smoothing option.' },
  { id: 'ribbon', type: 'bool', title: 'Ribbon?', defval: true, group: G_STOCH, inline: 'Stoch Draw States' },
  { id: 'smoothK', type: 'int', title: 'Smoothing K', defval: 3, min: 1, group: G_STOCH },
  { id: 'smoothD', type: 'int', title: 'Smoothing D', defval: 3, min: 1, group: G_STOCH },
  { id: 'stochLen', type: 'int', title: 'Stochastic Length', defval: 14, min: 1, group: G_STOCH },
  { id: 'stochFit', type: 'int', title: 'Stoch Scaling %', defval: 80, min: 1, max: 100, group: G_STOCH,
    tooltip: 'Adjusts the vertical scaling of the stochastic.' },
  { id: 'upper', type: 'int', title: 'OB', defval: 20, min: 1, max: 50, group: G_CHAN, inline: 'OB' },
  { id: 'upperx', type: 'int', title: 'OB Extreme', defval: 30, min: 1, max: 50, group: G_CHAN, inline: 'OB' },
  { id: 'lower', type: 'int', title: 'OS', defval: -20, min: -50, max: -1, group: G_CHAN, inline: 'OS' },
  { id: 'lowerx', type: 'int', title: 'OS Extreme', defval: -30, min: -50, max: -1, group: G_CHAN, inline: 'OS' },
  { id: 'showCbcBg', type: 'bool', title: 'Show CBC Background?', defval: true, group: G_CBC },
  { id: 'showCbcShapes', type: 'bool', title: 'Show CBC Shapes?', defval: true, group: G_CBC },
];

const COL_HIST = String(color.new(color.silver, 80));
const COL_SHADOW = color.rgb(0, 0, 0, 20);
const COL_NONE = color.rgb(0, 0, 0, 100);
const COL_RSI = color.rgb(250, 200, 50, 0);
const COL_STOCH_K = String(color.new('#0094FF', 0));
const COL_STOCH_D = String(color.new('#FF6A00', 0));
const COL_STOCH_K_FILL = String(color.new(COL_STOCH_K, 50));
const COL_STOCH_D_FILL = String(color.new(COL_STOCH_D, 50));
const COL_BULL_BG = color.rgb(255, 235, 59, 85);
const COL_BEAR_BG = color.rgb(5, 185, 240, 85);
const COL_BEARS = color.rgb(228, 102, 102);
const COL_BULLS = color.rgb(120, 206, 176);
const COL_EXTREME = String(color.new(color.silver, 60));
const COL_BAND = String(color.new(color.silver, 80));
const FILL_OB = String(color.new(color.red, 90));
const FILL_CHANNEL = String(color.new(color.blue, 90));
const FILL_OS = String(color.new(color.green, 90));

// Stoch plots: color = not i_ribbon ? colShadow / colStochK / colStochD : colNone (transparent with the default ribbon)
export const plotConfig: PlotConfig[] = [
  { id: 'plot0', title: 'RSI Histogram', color: COL_HIST, lineWidth: 1, style: 'histogram' },
  { id: 'plot1', title: 'RSI Shadow', color: COL_SHADOW, lineWidth: 3 },
  { id: 'plot2', title: 'RSI Overlay', color: COL_RSI, lineWidth: 1 },
  { id: 'plot3', title: 'Stoch K Shadow', color: COL_SHADOW, lineWidth: 3 },
  { id: 'plot4', title: 'Stoch D Shadow', color: COL_SHADOW, lineWidth: 3 },
  { id: 'plot5', title: 'Stoch K', color: COL_STOCH_K, lineWidth: 1 },
  { id: 'plot6', title: 'Stoch D', color: COL_STOCH_D, lineWidth: 1 },
];

/** plotcandle(O, H, L, C, "HARSI", ...) */
export const plotCandleConfig = [{ id: 'harsi', title: 'HARSI' }];

/** hline(i_upperx / i_upper / 0 / i_lower / i_lowerx) with the default inputs (Pine default line style: dashed) */
export const hlineConfig: HLineConfig[] = [
  { id: 'hline_upperx', price: 30, title: 'OB Extreme', color: COL_EXTREME, linestyle: 'dashed' },
  { id: 'hline_upper', price: 20, title: 'OB', color: COL_BAND, linestyle: 'dashed' },
  { id: 'hline_median', price: 0, title: 'Median', color: color.orange, linestyle: 'dotted' },
  { id: 'hline_lower', price: -20, title: 'OS', color: COL_BAND, linestyle: 'dashed' },
  { id: 'hline_lowerx', price: -30, title: 'OS Extreme', color: COL_EXTREME, linestyle: 'dashed' },
];

export const fillConfig: FillConfig[] = [
  { id: 'fill_ob', plot1: 'hline_upper', plot2: 'hline_upperx', color: FILL_OB, title: 'Background Fill OB' },
  { id: 'fill_channel', plot1: 'hline_upper', plot2: 'hline_lower', color: FILL_CHANNEL, title: 'Background Channel' },
  { id: 'fill_os', plot1: 'hline_lower', plot2: 'hline_lowerx', color: FILL_OS, title: 'Background Fill OS' },
];

export const metadata = {
  title: 'HARSI+CBC',
  shortTitle: 'HARSI+CBC',
  overlay: false,
};

/** Pine float comparisons: a > b only when a - b > 1e-10 (na compares false) */
const EPS = 1e-10;
const gt = (a: number, b: number) => a - b > EPS;
const lt = (a: number, b: number) => b - a > EPS;
const ge = (a: number, b: number) => !isNaN(a) && !isNaN(b) && !(b - a > EPS);

export function calculate(
  bars: Bar[],
  inputs: Partial<HarsiCbcInputs> = {},
): Omit<IndicatorResult, 'markers'> & {
  markers: MarkerData[];
  plotCandles: Record<string, PlotCandleData[]>;
  bgColors: BgColorData[];
} {
  const cfg = { ...defaultInputs, ...inputs };
  const n = bars.length;
  const A = (s: Series) => s.toArray().map((v) => v ?? NaN);
  const S = (a: number[]) => Series.fromArray(bars, a);

  // var bool cbc = false: flips on a close below the previous low / above the previous high
  const cbc: boolean[] = new Array(n);
  let state = false;
  for (let i = 0; i < n; i++) {
    const c = bars[i].close;
    const lowPrev = i > 0 ? bars[i - 1].low : NaN;
    const highPrev = i > 0 ? bars[i - 1].high : NaN;
    if (state && lt(c, lowPrev)) state = false;
    else if (!state && gt(c, highPrev)) state = true;
    cbc[i] = state;
  }

  // f_zrsi(src, len) = ta.rsi(src, len) - 50
  const zrsi = (src: Series, len: number) => A(ta.rsi(src, len)).map((v) => v - 50.0);

  // f_rsi(i_source, i_lenRSI, i_mode): _smoothed := na(_smoothed[1]) ? _zrsi : (_smoothed[1] + _zrsi) / 2
  const zrsiPlot = zrsi(getSourceSeries(bars, cfg.source), cfg.lenRSI);
  const smoothed: number[] = new Array(n);
  for (let i = 0; i < n; i++) {
    const prev = i > 0 ? smoothed[i - 1] : NaN;
    smoothed[i] = isNaN(prev) ? zrsiPlot[i] : (prev + zrsiPlot[i]) / 2.0;
  }
  const rsi = cfg.mode ? smoothed : zrsiPlot;

  // f_zstoch(RSI, i_stochLen, i_smoothK, i_stochFit); StochD = ta.sma(StochK, i_smoothD)
  const rsiS = S(rsi);
  const zstoch = A(ta.stoch(rsiS, rsiS, rsiS, cfg.stochLen)).map((v) => v - 50.0);
  const stochK = A(ta.sma(S(zstoch), cfg.smoothK)).map((v) => (v / 100.0) * cfg.stochFit);
  const stochD = A(ta.sma(S(stochK), cfg.smoothD));

  // f_rsiHeikinAshi(i_lenHARSI)
  const len = cfg.lenHARSI;
  const s = cfg.smoothing;
  const closeRSI = zrsi(new Series(bars, (b) => b.close), len);
  const highRaw = zrsi(new Series(bars, (b) => b.high), len);
  const lowRaw = zrsi(new Series(bars, (b) => b.low), len);
  const O: number[] = new Array(n);
  const H: number[] = new Array(n);
  const L: number[] = new Array(n);
  const C: number[] = new Array(n);
  for (let i = 0; i < n; i++) {
    const prevClose = i > 0 ? closeRSI[i - 1] : NaN;
    const openRSI = isNaN(prevClose) ? closeRSI[i] : prevClose; // nz(_closeRSI[1], _closeRSI)
    const highRSI = Math.max(highRaw[i], lowRaw[i]);
    const lowRSI = Math.min(highRaw[i], lowRaw[i]);
    C[i] = (openRSI + highRSI + lowRSI + closeRSI[i]) / 4.0;
    // _open := na(_open[i_smoothing]) ? (_openRSI + _closeRSI) / 2 : ((_open[1] * i_smoothing) + _close[1]) / (i_smoothing + 1)
    const openBack = i - s >= 0 ? O[i - s] : NaN;
    O[i] = isNaN(openBack) ? (openRSI + closeRSI[i]) / 2.0 : (O[i - 1] * s + C[i - 1]) / (s + 1);
    H[i] = Math.max(highRSI, Math.max(O[i], C[i]));
    L[i] = Math.min(lowRSI, Math.min(O[i], C[i]));
  }

  const candles: PlotCandleData[] = [];
  const bgColors: BgColorData[] = [];
  const markers: MarkerData[] = [];
  const stochFill: string[] = new Array(n);
  for (let i = 0; i < n; i++) {
    const t = bars[i].time;
    // plotcandle(O, H, L, C, "HARSI", bodyColour, wickColour, bordercolor = bodyColour): no candle when a value is na
    if ([O[i], H[i], L[i], C[i]].every((v) => !isNaN(v))) {
      const body = gt(C[i], O[i]) ? cfg.colUp : cfg.colDown;
      candles.push({ time: t, open: O[i], high: H[i], low: L[i], close: C[i], color: body, wickColor: cfg.colWick,
        borderColor: body });
    }
    // cbc[1] of the first bar is false (bool history)
    const prev = i > 0 ? cbc[i - 1] : false;
    const bullFlip = cbc[i] && !prev;
    const bearFlip = !cbc[i] && prev;
    if (cfg.showCbcBg && bullFlip) bgColors.push({ time: t, color: COL_BULL_BG });
    else if (cfg.showCbcBg && bearFlip) bgColors.push({ time: t, color: COL_BEAR_BG });
    if (cfg.showCbcShapes && bearFlip) {
      markers.push({ time: t, position: 'aboveBar', shape: 'triangleDown', color: COL_BEARS, size: 'small' });
    }
    if (cfg.showCbcShapes && bullFlip) {
      markers.push({ time: t, position: 'belowBar', shape: 'triangleUp', color: COL_BULLS, size: 'small' });
    }
    // fill(plot_stochK, plot_stochD, i_ribbon ? colStochFill : na)
    stochFill[i] = cfg.ribbon ? (ge(stochK[i], stochD[i]) ? COL_STOCH_K_FILL : COL_STOCH_D_FILL) : 'transparent';
  }

  const line = (f: (i: number) => number, c: string) => bars.map((b, i) => ({ time: b.time, value: f(i), color: c }));
  const stochShadow = !cfg.ribbon ? COL_SHADOW : COL_NONE;
  const constant = <T>(v: T) => new Array<T>(n).fill(v);

  return {
    metadata: { title: metadata.title, shorttitle: metadata.shortTitle, overlay: metadata.overlay },
    plots: {
      plot0: line((i) => (cfg.showHist ? rsi[i] : NaN), COL_HIST),
      plot1: line((i) => (cfg.showPlot ? rsi[i] : NaN), COL_SHADOW),
      plot2: line((i) => (cfg.showPlot ? rsi[i] : NaN), COL_RSI),
      plot3: line((i) => (cfg.showStoch ? stochK[i] : NaN), stochShadow),
      plot4: line((i) => (cfg.showStoch ? stochD[i] : NaN), stochShadow),
      plot5: line((i) => (cfg.showStoch ? stochK[i] : NaN), !cfg.ribbon ? COL_STOCH_K : COL_NONE),
      plot6: line((i) => (cfg.showStoch ? stochD[i] : NaN), !cfg.ribbon ? COL_STOCH_D : COL_NONE),
    },
    hlines: [
      { value: cfg.upperx, options: { title: 'OB Extreme', color: COL_EXTREME, linestyle: 'dashed' } },
      { value: cfg.upper, options: { title: 'OB', color: COL_BAND, linestyle: 'dashed' } },
      { value: 0, options: { title: 'Median', color: color.orange, linestyle: 'dotted' } },
      { value: cfg.lower, options: { title: 'OS', color: COL_BAND, linestyle: 'dashed' } },
      { value: cfg.lowerx, options: { title: 'OS Extreme', color: COL_EXTREME, linestyle: 'dashed' } },
    ],
    fills: [
      { plot1: 'hline_upper', plot2: 'hline_upperx', options: { title: 'Background Fill OB' }, colors: constant(FILL_OB) },
      { plot1: 'hline_upper', plot2: 'hline_lower', options: { title: 'Background Channel' }, colors: constant(FILL_CHANNEL) },
      { plot1: 'hline_lower', plot2: 'hline_lowerx', options: { title: 'Background Fill OS' }, colors: constant(FILL_OS) },
      { plot1: 'plot5', plot2: 'plot6', options: { title: 'Stoch Ribbon' }, colors: stochFill },
    ],
    markers,
    plotCandles: { harsi: candles },
    bgColors,
  };
}

export const HarsiCbc = {
  calculate,
  metadata,
  defaultInputs,
  inputConfig,
  plotConfig,
  plotCandleConfig,
  hlineConfig,
  fillConfig,
};
